#!/usr/bin/env bash

set -euo pipefail

# assing variable
DOTFILES_PATH="$HOME/.dotfiles"

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

source "$DOTFILES_PATH/scripts/core/_main.sh"
source "$DOTFILES_PATH/scripts/self/utils/install.sh"

##? Install the dotfiles
#?? 1.0.0
##?
##? Usage:
##?    install

# TODO docpars, dotbot, brew necesitan ser instalados previamente
echo "TODO docpars, dotbot, brew necesitan ser instalados previamente"

docs::parse "$@"

"$DOTFILES_PATH/bin/dot" self update

# TODO sustituir por instalación de starship
# log::note "💻 Installing Zim Framework for ZSH"
# source ~/.dotfiles/modules/zimfw/zimfw.zsh install

if platform::is_macos; then
  log::note "🍎 Installing MacOS custom packages"

  read -rp "🌍 Network: Which name do you want to give to this computer? " network_computer_name
  install_macos_custom "$network_computer_name"
fi

if platform::is_linux; then
  log::note "🐧 Installing Linux custom packages"

  install_linux_custom
fi

log::note "🐍 Installing python packages"
pip install -r "$DOTFILES_PATH/langs/python/requirements.txt" || true
pip install -r "$DOTFILES_PATH/langs/python/requirements.txt"

log::note "🐘 Installing php packages"
composer global install

log::note "🌈 Installing npm packages"
xargs npm install -g <"$DOTFILES_PATH/langs/js/global_modules.txt"

log::note "💻 Setting ZSH as the default shell"
command -v zsh | sudo tee -a /etc/shells
chsh -s "$(command -v zsh)"

log::note "🔀 Setting Git config"
read -rp "✉️ What is you email? " git_email
read -rp "👤 And your name? " git_name
read -rp "🔑 Aaaand… the ID of the signing key? " git_key_id

git config --global user.email "$git_email"
git config --global user.name "$git_name"
git config --global user.signingkey "$git_key_id"
git config --global --unset user.signingkey
git config --global --unset commit.gpgsign
git config --global --unset tag.gpgsign
git config --global --unset gpg.program

log::success "🎉 Done!"
