#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES/scripts/core/_main.sh"

##? List contributors with number of commits
#?? 1.0.0
##?
##? Usage:
##?    contributors

docs::parse "$@"

git shortlog --summary --numbered
