#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES/scripts/core/_main.sh"

##? Short the current $PWD
#?? 1.0.0
##?
##? Usage:
##?    short_pwd

docs::parse "$@"

if [[ $(pwd) == $HOME ]] ; then
  echo "~"
else
  echo ${${${:-/${(j:/:)${(M)${(s:/:)${(D)PWD:h}}#(|.)[^.]}}/${PWD:t}}//\/~/\~}/\/\//\/}
fi
