#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES/scripts/core/_main.sh"

##? Add intellij Code Templates symlink (since it's not synced via JetBrains Toolbox)
#?? 1.0.0
##?
##? Usage:
##?    add_code_templates

docs::parse "$@"

preferences_dir="$HOME/Library/Preferences"
intellij_version=$(ls "$preferences_dir" | grep 'IntelliJIdea' | sort -r | head -n 1)
intellij_code_templates_folder="$preferences_dir/$intellij_version/fileTemplates"

rm -rf "$intellij_code_templates_folder"
ln -s -i "$DOTFILES/editors/intellij/Code Templates/" "$intellij_code_templates_folder"

echo "Done for $intellij_version!"
