#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES/scripts/core/_main.sh"

##? Show the public ip
#?? 1.0.0
##?
##? Usage:
##?    ip

docs::parse "$@"

dig +short myip.opendns.com @resolver1.opendns.com
