# TMUX Theme based in tmux-power with my own modifications
# TMUX Custom Power Theme

# Config options

## Prefix key
set -g prefix C-a
set -g prefix2 C-b

## Status position
set -g status-position top

## Base number for pane and windows
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# history limit and mouse
set -g mouse on
set -g history-limit 10000

## Color Theme
set -g @tmux_power_theme 'everforest' # gold, everforest, moon, coral, snow, forest, violet, redwine, #HEXCODE

## Info format
set -g @tmux_power_date_format '%m/%d/%Y'
set -g @tmux_power_time_format '%-I:%M %p'

## Icons - set it to a blank for disabled it
set -g @tmux_power_date_icon ' ' # set it to a blank will disable the icon
set -g @tmux_power_time_icon ' ' # set it to a blank will disable the icon
set -g @tmux_power_user_icon           ' '
set -g @tmux_power_session_icon        ' '
# set -g @tmux_power_right_arrow_icon    ''
# set -g @tmux_power_left_arrow_icon     ''
# set -g @tmux_power_upload_speed_icon   '󰕒'
# set -g @tmux_power_download_speed_icon '󰇚'

## Info: user, host and session
set -g @tmux_power_show_user    true # show user
set -g @tmux_power_show_host    true # show host
set -g @tmux_power_show_session true # show session

## Call the config - need to be the last one
# run-shell "~/.dotfiles/terminal/tmux/themes/custom/custom.tmux"
# run-shell "~/WORK/42/dotfiles-42/config/tmux/custom.tmux"
run-shell "./custom.tmux"

